### ISSUE TITLE
How can i test it on pretrained model

### ISSUE THREAD

**Issue by Ratnadeep22** [chiawen/activity-anticipation#1]
Great job @chiawen... I just want to test the activity anticipation on pretrained model... How can i do that?... thanks in advance....

**Comment by deamonDevs** [comment]
how can i test the pretrained model?

**Comment by chiawen** [comment]
Hi, I did not have the testing code here but you can do testing by modifying my code. First, you have to save a checkpoint after training. Then, you initialize the network with that checkpoint to do inference.
